"""Initial schema

Revision ID: 49366d19c837
Revises: 
Create Date: 2026-09-03 01:08:26.771261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49366d19c837'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('MALE', 'FEMALE', 'MIXED', name='hostelcategory'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'BLOCKED', name='accommodationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostels_code'), 'hostels', ['code'], unique=True)
    op.create_table('penalty_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('penalty_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('preference_score_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preference_rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preference_rank')
    )
    op.create_table('priority_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('maximum_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'BLOCKED', name='accommodationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostel_id', 'code', name='uq_block_code_per_hostel')
    )
    op.create_index(op.f('ix_blocks_hostel_id'), 'blocks', ['hostel_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_session', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'OPTIMAL', 'FEASIBLE', 'INFEASIBLE', 'TIME_LIMIT', 'UNKNOWN', 'FAILED', 'CANCELLED', name='optimizationstatus'), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('solver', sa.String(length=50), nullable=False),
    sa.Column('applicant_count', sa.Integer(), nullable=False),
    sa.Column('bed_space_count', sa.Integer(), nullable=False),
    sa.Column('allocated_count', sa.Integer(), nullable=False),
    sa.Column('unallocated_count', sa.Integer(), nullable=False),
    sa.Column('objective_score', sa.Float(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('rule_set_version', sa.String(length=30), nullable=True),
    sa.Column('solver_time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_academic_session'), 'optimization_runs', ['academic_session'], unique=False)
    op.create_table('rule_set_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_label')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('faculty', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('programme', sa.String(length=150), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('academic_session', sa.String(length=20), nullable=False),
    sa.Column('year_of_entry', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'GRADUATED', 'SUSPENDED', 'WITHDRAWN', name='studentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_session', sa.String(length=20), nullable=False),
    sa.Column('application_reference', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('eligibility_status', sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', 'PENDING_VERIFICATION', name='eligibilitystatus'), nullable=False),
    sa.Column('preferred_room_type', sa.String(length=30), nullable=True),
    sa.Column('has_special_accommodation_requirement', sa.Boolean(), nullable=False),
    sa.Column('special_accommodation_note', sa.Text(), nullable=True),
    sa.Column('special_requirement_status', sa.Enum('NONE', 'PENDING_VERIFICATION', 'VERIFIED', name='requirementverificationstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_reference'),
    sa.UniqueConstraint('student_id', 'academic_session', name='uq_one_application_per_session')
    )
    op.create_index(op.f('ix_applications_academic_session'), 'applications', ['academic_session'], unique=False)
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'BLOCKED', name='accommodationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'name', name='uq_floor_name_per_block')
    )
    op.create_index(op.f('ix_floors_block_id'), 'floors', ['block_id'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_session', sa.String(length=20), nullable=False),
    sa.Column('priority_position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_session', name='uq_waitlist_student_session')
    )
    op.create_table('hostel_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('preference_rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'hostel_id', name='uq_hostel_once_per_application'),
    sa.UniqueConstraint('application_id', 'preference_rank', name='uq_rank_once_per_application')
    )
    op.create_index(op.f('ix_hostel_preferences_application_id'), 'hostel_preferences', ['application_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=30), nullable=False),
    sa.Column('room_type', sa.Enum('SINGLE', 'DOUBLE', 'TRIPLE', 'FOUR_PERSON', 'SIX_PERSON', 'OTHER', name='roomtype'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'BLOCKED', name='accommodationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'room_number', name='uq_room_number_per_floor')
    )
    op.create_index(op.f('ix_rooms_floor_id'), 'rooms', ['floor_id'], unique=False)
    op.create_table('student_priority_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('calculation_version', sa.String(length=30), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('incomplete_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_student_priority_scores_student_id'), 'student_priority_scores', ['student_id'], unique=False)
    op.create_table('unallocated_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('NO_AVAILABLE_BED', 'NO_COMPATIBLE_HOSTEL', 'NO_VALID_ASSIGNMENT', 'CAPACITY_EXHAUSTED', 'INELIGIBLE', 'OTHER', name='unallocatedreason'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unallocated_records_optimization_run_id'), 'unallocated_records', ['optimization_run_id'], unique=False)
    op.create_table('bed_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('bed_identifier', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'MAINTENANCE', 'BLOCKED', name='bedstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'bed_identifier', name='uq_bed_identifier_per_room')
    )
    op.create_index(op.f('ix_bed_spaces_room_id'), 'bed_spaces', ['room_id'], unique=False)
    op.create_table('priority_score_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority_score_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['priority_criteria.id'], ),
    sa.ForeignKeyConstraint(['priority_score_id'], ['student_priority_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priority_score_details_priority_score_id'), 'priority_score_details', ['priority_score_id'], unique=False)
    op.create_table('allocation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('academic_session', sa.String(length=20), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('bed_space_id', sa.Integer(), nullable=False),
    sa.Column('allocation_score', sa.Float(), nullable=False),
    sa.Column('preference_rank', sa.Integer(), nullable=True),
    sa.Column('allocation_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'CANCELLED', 'SUPERSEDED', 'RELEASED', name='allocationstatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bed_space_id'], ['bed_spaces.id'], ),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_results_academic_session'), 'allocation_results', ['academic_session'], unique=False)
    op.create_index(op.f('ix_allocation_results_bed_space_id'), 'allocation_results', ['bed_space_id'], unique=False)
    op.create_index(op.f('ix_allocation_results_optimization_run_id'), 'allocation_results', ['optimization_run_id'], unique=False)
    op.create_index(op.f('ix_allocation_results_student_id'), 'allocation_results', ['student_id'], unique=False)
    op.create_table('allocation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('previous_state', sa.Text(), nullable=True),
    sa.Column('new_state', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocation_results.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_history_allocation_id'), 'allocation_history', ['allocation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocation_history_allocation_id'), table_name='allocation_history')
    op.drop_table('allocation_history')
    op.drop_index(op.f('ix_allocation_results_student_id'), table_name='allocation_results')
    op.drop_index(op.f('ix_allocation_results_optimization_run_id'), table_name='allocation_results')
    op.drop_index(op.f('ix_allocation_results_bed_space_id'), table_name='allocation_results')
    op.drop_index(op.f('ix_allocation_results_academic_session'), table_name='allocation_results')
    op.drop_table('allocation_results')
    op.drop_index(op.f('ix_priority_score_details_priority_score_id'), table_name='priority_score_details')
    op.drop_table('priority_score_details')
    op.drop_index(op.f('ix_bed_spaces_room_id'), table_name='bed_spaces')
    op.drop_table('bed_spaces')
    op.drop_index(op.f('ix_unallocated_records_optimization_run_id'), table_name='unallocated_records')
    op.drop_table('unallocated_records')
    op.drop_index(op.f('ix_student_priority_scores_student_id'), table_name='student_priority_scores')
    op.drop_table('student_priority_scores')
    op.drop_index(op.f('ix_rooms_floor_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_hostel_preferences_application_id'), table_name='hostel_preferences')
    op.drop_table('hostel_preferences')
    op.drop_table('waitlist_entries')
    op.drop_index(op.f('ix_floors_block_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_academic_session'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('rule_set_versions')
    op.drop_index(op.f('ix_optimization_runs_academic_session'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_blocks_hostel_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('priority_criteria')
    op.drop_table('preference_score_configs')
    op.drop_table('penalty_configs')
    op.drop_index(op.f('ix_hostels_code'), table_name='hostels')
    op.drop_table('hostels')
    # ### end Alembic commands ###
